const TEST1 = 'TEST1'
const TEST2 = 'TEST2'
const CLEARDATA = 'CLEARDATA'
const SAVEIMG = 'SAVEIMG'
const SAVEFORMDATA = 'SAVEFORMDATA'
const LOGIN_SUCESS = 'LOGIN_SUCESS'
export {
    TEST1,
    TEST2,
    CLEARDATA,
    SAVEIMG,
    SAVEFORMDATA,
    LOGIN_SUCESS
}
